builds:
  as:
    composite: 3111111
    dungeons: 3131111
  sc:
    composite: 3111311
    dungeons: 3131311
sims:
  racials:
    files:
      - racials.simc
  trinkets:
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
compositeWeights: weightsCastleNathria
singleTargetWeights: weightsSingle
simcBuild: nightly
defaultIterations: 10000
raidbots:
  apiUrlBase: https://www.raidbots.com
  numOfRetries: 2
  retryInterval: 20