builds:
  am:
    composite: 3121121
    dungeons: 3131311
  stm:
    composite: 3121123
    dungeons: 3131313
covenants:
  - kyrian
  - night_fae
  - venthyr
  - necrolord
sims:
  apl:
    builds: false
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  conduits:
    builds: true
    covenant: 
      lookup: true
      files: true
    lookupType: spell
    steps:
      - DPS
    files:
      - kyrian.simc
      - necrolord.simc
      - night_fae.simc
      - venthyr.simc
  consumables:
    builds: true
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  covenants:
    builds: true
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - covenants.simc
  enchants:
    builds: true
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - enchants.simc
  legendaries:
    builds: true
    covenants:
      lookup: true
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - legendaries.simc
  racials:
    builds: true
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  soulbinds:
    builds: true
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - necrolord.simc
  stats:
    builds: true
    covenant:
      lookup: false
      files: false
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    builds: false
    covenant:
      lookup: false
      files: false
    lookupType: spell
    steps:
      - DPS
    files:
      - AM.simc
      - LotV.simc
      - STM.simc
  trinkets:
    builds: true
    covenant:
      lookup: false
      files: false
    lookupType: item
    steps:
      - 130
      - 135
      - 155
      - 157
      - 165
      - 170
      - 183
      - 187
      - 200
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
compositeWeights: weightsCastleNathria
singleTargetWeights: weightsSingle
simcBuild: nightly
defaultIterations: 10000
raidbots:
  apiUrlBase: https://mimiron.raidbots.com
  numOfRetries: 2
  retryInterval: 20
analyze:
  markdown: true
  csv: true
  json: true
stats:
  base: 400
  steps: 100
  total: 1400
  include:
    - mastery
    - haste
    - crit
    - versatility
