builds:
  as:
    composite: 3111111
    dungeons: 3131111
  sc:
    composite: 3111311
    dungeons: 3131311
sims:
  apl:
    builds: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  consumables:
    builds: true
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  enchants:
    builds: true
    lookupType: spell
    steps:
      - DPS
    files:
      - enchants.simc
  racials:
    builds: true
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  talents:
    builds: false
    lookupType: spell
    steps:
      - DPS
    files:
      - DA.simc
      - LotV.simc
      - STM.simc
  trinkets:
    builds: true
    lookupType: item
    steps:
      - 415
      - 420
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
compositeWeights: weightsCastleNathria
singleTargetWeights: weightsSingle
simcBuild: nightly
defaultIterations: 10000
raidbots:
  apiUrlBase: https://www.raidbots.com
  numOfRetries: 2
  retryInterval: 20
analyze:
  markdown: true
  csv: true
  json: true
